INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(10001, 'didannguyen', 'Learn Spring Boot', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(10002, 'didannguyen', 'Learn NextJS', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(10003, 'didannguyen', 'Learn AWS', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(10004, 'didannguyen', 'Learn CCIE', CURRENT_DATE(), false);