spring.application.name=GraphQL

spring.graphql.schema.locations=classpath:graphql/custom-type
spring.graphql.http.path=/graphql

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql