spring.application.name=GraphQL

spring.graphql.schema.locations=classpath:graphql/validate-input-error-handling
spring.graphql.http.path=/graphql
spring.graphql.websocket.path=/graphql

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

customer.service.url=http://localhost:8080/graphql
customer.events.subscription.url=ws://localhost:8080/graphql