spring:
  application:
    name: second
  datasource:
    url: jdbc:mariadb://localhost:3307/log
    username: test
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

grpc:
  server:
    port: 9090
