package=r2dbc

spring.application.name=reactive

# C?u hình r2dbc ?ên th? m?c ch?a file sql kh?i t?o (nêu c?n ch?y khi kh?i ??ng ?ng d?ng)
spring.sql.init.data-locations=classpath:sql/data.sql
spring.r2dbc.url=r2dbc:h2:mem:///./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=