package=router

spring.application.name=router

# C?u hình r2dbc ?ên th? m?c ch?a file sql kh?i t?o (nêu c?n ch?y khi kh?i ??ng ?ng d?ng)
spring.sql.init.data-locations=classpath:sql/data.sql

# C?u hình k?t n?i R2DBC ??n c? s? d? li?u H2 trong b? nh?
spring.r2dbc.url=r2dbc:h2:mem:///./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# C?u hình log ?? hi?n th? các câu l?nh SQL ???c th?c thi
logging.level.org.springframework.r2dbc="DEBUG"