server:
  port: 8080
spring:
  application:
    name: first
  datasource:
    url: jdbc:mariadb://localhost:3307/log
    username: test
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

app:
  rest:
    third-url: http://localhost:8081/api/v1/rest-api

grpc:
  client:
    second:
      address: static://localhost:9090
  server:
    port: 9091