server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/danprohy/configserver-microservices.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "ff1e5a8caca2b09be73ac311a464be7d"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # Nhóm metrics theo tên service để dễ quản lý

logging:
  level:
    com:
      didan:
        microservices:
          configserver: debug # Log các thông tin debug của Config Server Service
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
