services:
   accounts:
      image: "dannguyenmessi/accounts-bank:v1"
      container_name: "accounts-ms"
      ports:
         - "8080:8080"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
         - didan
   loans:
      image: "dannguyenmessi/loans-bank:v1"
      container_name: "loans-ms"
      ports:
         - "8090:8090"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
         - didan
   cards:
      image: "dannguyenmessi/cards-bank:v1"
      container_name: "cards-ms"
      ports:
         - "9000:9000"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
         - didan
networks:
   didan:
      driver: "bridge"