server:
  port: 9010

spring:
  application:
    name: "messages"
  cloud:
    function:
      definition: email|sms # Gop 2 function email va sms thanh 1 function voi entrypoint la emailsms, no se goi 2 function email và sms cung 1 luc

