spring:
  application:
    name: LogQuickwit
    admin:
      enabled: true
  jmx:
    enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      access: read_only
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  jmx:
    metrics:
      export:
        enabled: true

otel:
  service:
    name: ${spring.application.name}
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317
      compression: gzip
      protocol: grpc






