{{- define "common.deployment" -}} # Định nghĩa template deployment
apiVersion: apps/v1 # Version dành cho Deployment
kind: Deployment # Loại cấu hình là Deployment
metadata:
  name: {{ .Values.deploymentName }} # Tên Deployment, lấy giá trị deploymentName từ file values.yaml
  labels: # Label cho Deployment
    app: {{ .Values.appLabel }} # Lấy giá trị appLabel từ file values.yaml
spec:
  replicas: {{ .Values.replicaCount }} # Số lượng Pod, lấy giá trị replicaCount từ file values.yaml
  selector: # Chọn Pod dựa trên label
    matchLabels:
      app: {{ .Values.appLabel }} # Lấy giá trị appLabel từ file values.yaml
  template: # Template Pod
    metadata:
      labels: # Label cho Pod
        app: {{ .Values.appLabel }} # Lấy giá trị appLabel từ file values.yaml
    spec:
      containers:
      - name: {{ .Values.appLabel }} # Tên Container, lấy giá trị appLabel từ file values.yaml
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # Image của Container, lấy giá trị repository và tag từ file values.yaml
        ports:
        - containerPort: {{ .Values.containerPort }} # Port của Container, lấy giá trị containerPort từ file values.yaml
          protocol: TCP # Giao thức sử dụng cho Container
        env:
        {{- if .Values.appname_enabled }} # Nếu có appname_enabled trong file values.yaml
        - name: SPRING_APPLICATION_NAME # Tên biến môi trường
          value: {{ .Values.appName }} # Giá trị biến môi trường, lấy giá trị appname từ file values.yaml
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.profile_enabled }} # Nếu có profile_enabled trong file values.yaml
        - name: SPRING_PROFILES_ACTIVE # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: SPRING_PROFILES_ACTIVE # Key của ConfigMap
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.config_enabled }} # Nếu có config_enabled trong file values.yaml
        - name: SPRING_CONFIG_IMPORT # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: SPRING_CONFIG_IMPORT # Key của ConfigMap
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.discoveryclient_enabled }} # Nếu có discoveryclient trong file values.yaml
        - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERY-SERVER-URL # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERY-SERVER-URL # Key của ConfigMap
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.resourceserver_enabled }} # Nếu có resourceserver_enabled trong file values.yaml
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI # Key của ConfigMap
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.otel_enabled }} # Nếu có otel_enabled trong file values.yaml
        - name: JAVA_TOOL_OPTIONS # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: JAVA_TOOL_OPTIONS # Key của ConfigMap
        - name: OTEL_EXPORTER_OTLP_ENDPOINT # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: OTEL_EXPORTER_OTLP_ENDPOINT # Key của ConfigMap
        - name: OTEL_METRICS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: OTEL_METRICS_EXPORTER # Key của ConfigMap
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.appName }}
        {{- end }} # Kết thúc điều kiện
        {{- if .Values.kafka_enabled }} # Nếu có kafka_enabled trong file values.yaml
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS # Tên biến môi trường
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }} # Tên ConfigMap, lấy giá trị configmapName từ file values.yaml
              key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS # Key của ConfigMap
        {{- end }} # Kết thúc điều kiện
{{- end -}} # Kết thúc định nghĩa template deployment