spring.application.name=Microservices Pattern

gateway_aggregator.product.service=http://localhost:7070/sec01/product/
gateway_aggregator.promotion.service=http://localhost:7070/sec01/promotion/
gateway_aggregator.review.service=http://localhost:7070/sec01/review/