spring.application.name=Microservices Pattern

gateway_aggregator.product.service=http://localhost:7070/sec01/product/
gateway_aggregator.promotion.service=http://localhost:7070/sec01/promotion/
gateway_aggregator.review.service=http://localhost:7070/sec01/review/

scatter_gather.delta.service=http://localhost:7070/sec02/delta/
scatter_gather.frontier.service=http://localhost:7070/sec02/frontier/
scatter_gather.jetblue.service=http://localhost:7070/sec02/jetblue/

orchestrator_parallel.product.service=http://localhost:7070/sec03/product/
orchestrator_parallel.user.service=http://localhost:7070/sec03/user/
orchestrator_parallel.inventory.service=http://localhost:7070/sec03/inventory/
orchestrator_parallel.shipping.service=http://localhost:7070/sec03/shipping/

orchestrator_sequence.product.service=http://localhost:7070/sec04/product/
orchestrator_sequence.user.service=http://localhost:7070/sec04/user/
orchestrator_sequence.inventory.service=http://localhost:7070/sec04/inventory/
orchestrator_sequence.shipping.service=http://localhost:7070/sec04/shipping/

splitter.car.service=http://localhost:7070/sec05/car/reserve
splitter.room.service=http://localhost:7070/sec05/room/reserve

timeout.product.service=http://localhost:7070/sec06/product/
timeout.review.service=http://localhost:7070/sec06/review/