---
apiVersion: v1
kind: List # Khai báo kiểu resource cần triển khai
items: # Khai báo các resource cần triển khai
  - apiVersion: v1  
    kind: Service # Khai báo kiểu resource là Service
    metadata: 
      labels:
        app: spring-cloud-kubernetes-discoveryserver # Nhãn của resource
      name: spring-cloud-kubernetes-discoveryserver # Tên của resource
    spec: # Khai báo thông tin cấu hình của resource
      ports:
        - name: http
          port: 80
          targetPort: 8761 # Port của container 
      selector: # Chọn các pod có nhãn app=spring-cloud-kubernetes-discoveryserver
        app: spring-cloud-kubernetes-discoveryserver 
      type: ClusterIP # Loại Service là ClusterIP, chỉ có thể truy cập từ trong cluster
  - apiVersion: v1 
    kind: ServiceAccount # Khai báo kiểu resource là ServiceAccount
    metadata: 
      labels:
        app: spring-cloud-kubernetes-discoveryserver # Nhãn của resource
      name: spring-cloud-kubernetes-discoveryserver 
  - apiVersion: rbac.authorization.k8s.io/v1 
    kind: RoleBinding # Khai báo kiểu resource là RoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver # Nhãn của resource
      name: spring-cloud-kubernetes-discoveryserver:view
    roleRef: # Phân quyền cho ServiceAccount
      kind: Role # Kiểu phân quyền
      apiGroup: rbac.authorization.k8s.io # Nhóm API
      name: namespace-reader # Tên của Role
    subjects: # Danh sách các ServiceAccount được phân quyền
      - kind: ServiceAccount  # Kiểu ServiceAccount
        name: spring-cloud-kubernetes-discoveryserver # Tên của ServiceAccount được phân quyền
  - apiVersion: rbac.authorization.k8s.io/v1 # Phiên bản API
    kind: Role # Kiểu resource
    metadata: # Thông tin metadata
      namespace: default # Namespace mà Role này thuộc về
      name: namespace-reader # Tên của Role
    rules: # Quy tắc phân quyền
      - apiGroups: ["", "extensions", "apps"] # Nhóm API
        resources: ["pods", "services", "endpoints"] # Resource được phân quyền
        verbs: ["get", "list", "watch"] # Các hành động được phân quyền 
  - apiVersion: apps/v1 # Phiên bản API
    kind: Deployment # Kiểu resource
    metadata:
      name: spring-cloud-kubernetes-discoveryserver-deployment # Tên của resource
    spec: # Thông tin cấu hình của resource
      selector:
        matchLabels: # Chọn các pod có nhãn app=spring-cloud-kubernetes-discoveryserver
          app: spring-cloud-kubernetes-discoveryserver 
      template: # Template của Pod
        metadata:
          labels:
            app: spring-cloud-kubernetes-discoveryserver  
        spec: # Thông tin cấu hình của Pod
          serviceAccountName: spring-cloud-kubernetes-discoveryserver # Tên của ServiceAccount
          containers: 
          - name: spring-cloud-kubernetes-discoveryserver # Tên của container
            image: springcloud/spring-cloud-kubernetes-discoveryserver:3.1.0 # Image của container, pull từ Docker Hub
            imagePullPolicy: IfNotPresent # Chính sách pull image nếu chưa có trên node
            readinessProbe: # Khai báo endpoint kiểm tra readiness của container, nếu container check fail thì sẽ restart container cho đến khi check pass
              httpGet: # Kiểu kiểm tra HTTP GET
                port: 8761 # Port của container
                path: /actuator/health/readiness # Endpoint kiểm tra readiness
              initialDelaySeconds: 100 # Thời gian chờ trước khi kiểm tra readiness
              periodSeconds: 30 # Chu kỳ kiểm tra readiness trong 30s
            livenessProbe: # Khai báo endpoint kiểm tra liveness của container, nếu container check fail thì sẽ restart container cho đến khi check pass
              httpGet: # Kiểu kiểm tra HTTP GET
                port: 8761 # Port của container
                path: /actuator/health/liveness # Endpoint kiểm tra liveness
              initialDelaySeconds: 100 # Thời gian chờ trước khi kiểm tra liveless
              periodSeconds: 30 # Chu kỳ kiểm tra liveness trong 30s
            ports: 
            - containerPort: 8761 # Port của container